-- MySQL Script generated by MySQL Workbench
-- 11/10/16 15:07:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alarme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alarme` (
  `idAlarme` SMALLINT NOT NULL AUTO_INCREMENT,
  `heure` INT NOT NULL,
  `minute` INT NOT NULL,
  `raison` DECIMAL(255) NULL,
  PRIMARY KEY (`idAlarme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sortie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sortie` (
  `idSortie` SMALLINT NOT NULL,
  `DateSortie` DATETIME NOT NULL,
  `DateRentrer` DATETIME NOT NULL,
  `raison` LONGTEXT NULL,
  `SortieAutoriser` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idSortie`),
  UNIQUE INDEX `SortieAutoriser_UNIQUE` (`SortieAutoriser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatient` SMALLINT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `port` SMALLINT NOT NULL,
  `adresseMac` VARCHAR(18) NOT NULL,
  `estPresent` TINYINT(1) NOT NULL,
  `idAlarme` SMALLINT NOT NULL,
  `idSortie` SMALLINT NOT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `idAlarme_idx` (`idAlarme` ASC),
  INDEX `idSortie_idx` (`idSortie` ASC),
  CONSTRAINT `idAlarme`
    FOREIGN KEY (`idAlarme`)
    REFERENCES `mydb`.`Alarme` (`idAlarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSortie`
    FOREIGN KEY (`idSortie`)
    REFERENCES `mydb`.`Sortie` (`idSortie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Infirmiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Infirmiere` (
  `idInfirmiere` SMALLINT NOT NULL AUTO_INCREMENT,
  `niveau` VARCHAR(85) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idInfirmiere`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
